behat.yml.dist

This pull request fixed Behat language switcher selector after language switcher theming has been merged in OE Theme as part of https://github.com/openeuropa/oe_theme/pull/70

OPENEUROPA-558: Fix language switcher selector

---

composer.json

Update code-review to version 0.3
- Changed: Update code-review to version 0.3

OPENEUROPA-721: Update code-review and grump.yml.dist file.

---

README.md

The README currently suggests to install the development version, but it is recommended to install the latest release instead.

Update README to suggest installation of stable release

---

config/install/language/hr/language.entity.hr.yml
tests/Behat/MinkContext.php
tests/features/language-switcher.feature

Add missing test for language translations.
- Added: Add missing test for language translations.

OPENEUROPA-1345: Add tests for language translations.

---

behat.yml.dist
composer.json
tests/features/interface-default-language.feature
tests/features/translation.feature

OPENEUROPA-1522: Make sure we don't use Drupal paths in Behat scenarios.

---

oe_multilingual.install

The description is in the code comment.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-1549: Ensuring config translations get added to locale.

---

.drone.yml
CHANGELOG.md
composer.json

Create the release 0.3.0

---

.drone.yml

Update container on drone and test the realease 8.7.0 of Drupal.
- Changed: drone.yml

OPENEUROPA-1766: Update container on drone.

---

CHANGELOG.md

Create release 0.4.2.
- Added:
- Changed: CHANGELOG.md
- Deprecated:
- Removed:
- Fixed:
- Security:

OPENEUROPA-1813: Create release 0.4.2.

---

CHANGELOG.md

Create release 1.0.0.
- Changed: Changelog file.

OPENEUROPA-1864: Create release 1.0.0.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Update CHANGELOG for release 1.1.2.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Update CHANGELOG for release 1.1.3.

---

CHANGELOG.md

OPENEUROPA-1766: Create release 1.1.4.

---

composer.json

OPENEUROPA-1766: Revert mink fix.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-0000: Prepare for 1.3.0 release.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Release-1.6.0: Update changelog for release 1.6.0.

---

oe_multilingual.module
src/Plugin/Block/ContentLanguageBlock.php

Move access check to appropriate method.
- Added:
- Changed: Move access check to appropriate method.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

[EWPP-1142] EWPP-1278: Move access check to appropriate method.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-0000: Prepare release 1.10.0.

---

composer.json

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP: Fix ctools version.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 1.11.0.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 1.16.0

---

composer.json

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-3905: Make sure to use phpunit 9.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 1.17.0.
